# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Wake Up
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       noindex, nofollow

  stylesheets:    [http://cdn.sencha.com/ext/beta/4.2.0.265//resources/css/ext-all.css,ext.css]

  javascripts:    [http://cdn.sencha.com/ext/beta/4.2.0.265/ext-all-debug.js, ext/App.js]

  has_layout:     true
  layout:         layout
