<?php

/**
 * logTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class logTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object logTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('log');
    }
}